include:
  - ../../../base/grafana/compose.yml

services:
  grafana:
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "http://grafana:3000"
      caddy.tls: /certs/${CERT_DOMAIN}/fullchain.pem /certs/${CERT_DOMAIN}/privkey.pem
      caddy.@forbidden.path: /metrics
      caddy.respond: "@forbidden 403"
    networks:
      - caddy
      - mailserver
    env_file:
      - path: override.env
        required: true

  grafana-renderer:
    env_file:
      - path: override.env
        required: true

networks:
  caddy:
    external: true
  mailserver:
    external: true

